spring.application.name=projetorh
# URL de conexão (o parâmetro final cria o banco automaticamente se ele não existir)
spring.datasource.url=jdbc:mysql://localhost:3306/projetorh_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# Usuário e Senha do seu MySQL instalado na máquina
spring.datasource.username=root
spring.datasource.password=root

# Driver do MySQL (indica ao Spring qual tradutor usar)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect